version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.web
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for hot reloading
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - ./package.json:/app/package.json
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - web_node_modules:/app/apps/web/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --filter=web
    stdin_open: true
    tty: true

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    dns:
      - 8.8.8.8
    ports:
      - '3001:3001'
    volumes:
      # Mount source code for hot reloading
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - ./turbo.json:/app/turbo.json
      - ./package.json:/app/package.json
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --filter=api
    stdin_open: true
    tty: true

volumes:
  node_modules:
  web_node_modules:
  api_node_modules:
  packages_node_modules:
