/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreatePostDto,
  PostControllerGetPostsByStatusParams,
  PostEntity,
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

export const postControllerCreate = (
  createPostDto: CreatePostDto,
  signal?: AbortSignal
) => {
  return customInstance<PostEntity>({
    url: `/post`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPostDto,
    signal,
  });
};

export const getPostControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postControllerCreate>>,
    TError,
    { data: CreatePostDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postControllerCreate>>,
  TError,
  { data: CreatePostDto },
  TContext
> => {
  const mutationKey = ['postControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postControllerCreate>>,
    { data: CreatePostDto }
  > = (props) => {
    const { data } = props ?? {};

    return postControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postControllerCreate>>
>;
export type PostControllerCreateMutationBody = CreatePostDto;
export type PostControllerCreateMutationError = unknown;

export const usePostControllerCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postControllerCreate>>,
    TError,
    { data: CreatePostDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postControllerCreate>>,
  TError,
  { data: CreatePostDto },
  TContext
> => {
  const mutationOptions = getPostControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const postControllerGetPostsByStatus = (
  params: PostControllerGetPostsByStatusParams,
  signal?: AbortSignal
) => {
  return customInstance<PostEntity[]>({
    url: `/post`,
    method: 'GET',
    params,
    signal,
  });
};

export const getPostControllerGetPostsByStatusQueryKey = (
  params?: PostControllerGetPostsByStatusParams
) => {
  return [`/post`, ...(params ? [params] : [])] as const;
};

export const getPostControllerGetPostsByStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof postControllerGetPostsByStatus>>,
  TError = unknown,
>(
  params: PostControllerGetPostsByStatusParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof postControllerGetPostsByStatus>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostControllerGetPostsByStatusQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postControllerGetPostsByStatus>>
  > = ({ signal }) => postControllerGetPostsByStatus(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof postControllerGetPostsByStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PostControllerGetPostsByStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof postControllerGetPostsByStatus>>
>;
export type PostControllerGetPostsByStatusQueryError = unknown;

export function usePostControllerGetPostsByStatus<
  TData = Awaited<ReturnType<typeof postControllerGetPostsByStatus>>,
  TError = unknown,
>(
  params: PostControllerGetPostsByStatusParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof postControllerGetPostsByStatus>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPostControllerGetPostsByStatusQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
