/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderResponseDtoAmount } from './createOrderResponseDtoAmount';
import type { CreateOrderResponseDtoNotes } from './createOrderResponseDtoNotes';

export interface CreateOrderResponseDto {
  id: string;
  entity: string;
  amount: CreateOrderResponseDtoAmount;
  amount_paid: number;
  amount_due: number;
  currency: string;
  receipt?: string;
  status: string;
  attempts: number;
  notes?: CreateOrderResponseDtoNotes;
  created_at: number;
}
