/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

/**
 * Social media platform
 */
export type CreateSocialAccountDtoPlatform =
  (typeof CreateSocialAccountDtoPlatform)[keyof typeof CreateSocialAccountDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSocialAccountDtoPlatform = {
  LINKEDIN: 'LINKEDIN',
  TWITTER: 'TWITTER',
} as const;
