/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { CreateSocialAccountDtoPlatform } from './createSocialAccountDtoPlatform';
import type { CreateSocialAccountDtoTokenType } from './createSocialAccountDtoTokenType';

export interface CreateSocialAccountDto {
  /** Social media platform */
  platform: CreateSocialAccountDtoPlatform;
  /** Platform user ID */
  platformId?: string;
  /** Platform username */
  username?: string;
  /** Display name on platform */
  displayName?: string;
  /** Avatar URL from platform */
  avatar?: string;
  /** Authentication protocol used */
  tokenType: CreateSocialAccountDtoTokenType;
  /** Access token for the platform API (OAuth1 or OAuth2) */
  accessToken: string;
  /** Access token secret (for OAuth1) */
  accessSecret?: string;
  /** Refresh token for the platform API (for OAuth2) */
  refreshToken?: string;
  /** Token expiration date (for OAuth2) */
  expiresAt?: string;
  /** Refresh token expiration date (for OAuth2) */
  refreshTokenExpiresAt?: string;
  /** Token expiration in seconds from now (for OAuth2) */
  expiresIn?: number;
  /** Whether account is active */
  isActive?: boolean;
}
