/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { CreatePostDtoPlatform } from './createPostDtoPlatform';

export interface CreatePostDto {
  /** @maxLength 280 */
  content: string;
  media?: string[];
  scheduledFor: string;
  socialAccountId: string;
  platform: CreatePostDtoPlatform;
}
