/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export interface LinkedInAccessTokenDto {
  /** The authorization code returned by LinkedIn */
  code: string;
  /** The redirect URI used in the initial authorization request */
  redirectUri: string;
}
