/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { PostEntityStatus } from './postEntityStatus';
import type { PostEntityPlatform } from './postEntityPlatform';

export interface PostEntity {
  id: string;
  content: string;
  media: string[];
  scheduledFor: string;
  status: PostEntityStatus;
  platform: PostEntityPlatform;
  socialAccountId: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  postedAt?: string | null;
  /** @nullable */
  failedReason?: string | null;
}
