/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export type PostEntityPlatform =
  (typeof PostEntityPlatform)[keyof typeof PostEntityPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostEntityPlatform = {
  LINKEDIN: 'LINKEDIN',
  TWITTER: 'TWITTER',
} as const;
