/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

/**
 * Authentication protocol used
 */
export type SocialAccountEntityTokenType =
  (typeof SocialAccountEntityTokenType)[keyof typeof SocialAccountEntityTokenType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialAccountEntityTokenType = {
  OAUTH1: 'OAUTH1',
  OAUTH2: 'OAUTH2',
} as const;
