/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { SocialAccountEntityPlatform } from './socialAccountEntityPlatform';
import type { SocialAccountEntityTokenType } from './socialAccountEntityTokenType';

export interface SocialAccountEntity {
  /** Social account ID */
  id: string;
  /** Social media platform */
  platform: SocialAccountEntityPlatform;
  /** Platform user ID */
  platformId: string;
  /** Platform username */
  username: string;
  /**
   * Display name on platform
   * @nullable
   */
  displayName?: string | null;
  /**
   * Avatar URL from platform
   * @nullable
   */
  avatar?: string | null;
  /** Authentication protocol used */
  tokenType: SocialAccountEntityTokenType;
  /** Access token for the platform API */
  accessToken: string;
  /**
   * Refresh token for the platform API (for OAuth2)
   * @nullable
   */
  refreshToken?: string | null;
  /**
   * Token expiration date (for OAuth2)
   * @nullable
   */
  expiresAt?: string | null;
  /** Whether account is active */
  isActive: boolean;
  /** Account creation date */
  createdAt: string;
  /** User ID this account belongs to */
  userId: string;
}
