/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export interface TwitterAccessTokenDto {
  code: string;
  state: string;
  codeVerifier: string;
  redirectUri: string;
}
