/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** User email address */
  email?: string;
  /** User full name */
  name?: string;
  /** User avatar URL */
  avatar?: string;
  /** User timezone */
  timezone?: string;
}
