/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { UserControllerGetUsersSortBy } from './userControllerGetUsersSortBy';
import type { UserControllerGetUsersSortOrder } from './userControllerGetUsersSortOrder';

export type UserControllerGetUsersParams = {
  /**
   * Number of records to skip
   * @minimum 0
   */
  skip?: number;
  /**
   * Number of records to take
   * @minimum 1
   * @maximum 100
   */
  take?: number;
  /**
   * Search by name or email
   */
  search?: string;
  /**
   * Sort field
   */
  sortBy?: UserControllerGetUsersSortBy;
  /**
   * Sort order
   */
  sortOrder?: UserControllerGetUsersSortOrder;
};
