/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export type UserControllerGetUserCountParams = {
  /**
   * Search by name or email
   */
  search?: string;
};
