/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */

export type UserControllerGetUserWithRecentPostsParams = {
  /**
   * Number of recent posts to include
   */
  limit?: number;
};
