/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import type { SocialAccountEntity } from './socialAccountEntity';
import type { PostEntity } from './postEntity';

export interface UserEntity {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /**
   * User full name
   * @nullable
   */
  name?: string | null;
  /**
   * User avatar URL
   * @nullable
   */
  avatar?: string | null;
  /** User timezone (IANA timezone identifier) */
  timezone: string;
  /** User creation date */
  createdAt: string;
  /** User last update date */
  updatedAt: string;
  /** User social accounts */
  socialAccounts?: SocialAccountEntity[];
  /** User posts */
  posts?: PostEntity[];
}
