/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from '.././mutator/custom-instance';

export const healthControllerHealthCheck = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/health`, method: 'GET', signal });
};

export const getHealthControllerHealthCheckQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthControllerHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerHealthCheck>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHealthControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerHealthCheck>>
  > = ({ signal }) => healthControllerHealthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthControllerHealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerHealthCheck>>
>;
export type HealthControllerHealthCheckQueryError = unknown;

export function useHealthControllerHealthCheck<
  TData = Awaited<ReturnType<typeof healthControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerHealthCheck>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthControllerHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
