/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateUserDto,
  UpdateUserDto,
  UserControllerGetUserCountParams,
  UserControllerGetUserWithRecentPostsParams,
  UserControllerGetUsersParams,
  UserEntity,
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

/**
 * @summary Create a new user
 */
export const userControllerCreateUser = (
  createUserDto: CreateUserDto,
  signal?: AbortSignal
) => {
  return customInstance<UserEntity>({
    url: `/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createUserDto,
    signal,
  });
};

export const getUserControllerCreateUserMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerCreateUser>>,
    TError,
    { data: CreateUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerCreateUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationKey = ['userControllerCreateUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerCreateUser>>,
    { data: CreateUserDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerCreateUser(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerCreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCreateUser>>
>;
export type UserControllerCreateUserMutationBody = CreateUserDto;
export type UserControllerCreateUserMutationError = void;

/**
 * @summary Create a new user
 */
export const useUserControllerCreateUser = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerCreateUser>>,
    TError,
    { data: CreateUserDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userControllerCreateUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationOptions = getUserControllerCreateUserMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get all users with optional filtering and pagination
 */
export const userControllerGetUsers = (
  params?: UserControllerGetUsersParams,
  signal?: AbortSignal
) => {
  return customInstance<UserEntity[]>({
    url: `/users`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUserControllerGetUsersQueryKey = (
  params?: UserControllerGetUsersParams
) => {
  return [`/users`, ...(params ? [params] : [])] as const;
};

export const getUserControllerGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUsers>>,
  TError = unknown,
>(
  params?: UserControllerGetUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUsers>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUsers>>
  > = ({ signal }) => userControllerGetUsers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUsers>>
>;
export type UserControllerGetUsersQueryError = unknown;

/**
 * @summary Get all users with optional filtering and pagination
 */

export function useUserControllerGetUsers<
  TData = Awaited<ReturnType<typeof userControllerGetUsers>>,
  TError = unknown,
>(
  params?: UserControllerGetUsersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUsers>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get current user
 */
export const userControllerGetMe = (signal?: AbortSignal) => {
  return customInstance<UserEntity>({
    url: `/users/me`,
    method: 'GET',
    signal,
  });
};

export const getUserControllerGetMeQueryKey = () => {
  return [`/users/me`] as const;
};

export const getUserControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetMe>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetMe>>
  > = ({ signal }) => userControllerGetMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetMe>>
>;
export type UserControllerGetMeQueryError = unknown;

/**
 * @summary Get current user
 */

export function useUserControllerGetMe<
  TData = Awaited<ReturnType<typeof userControllerGetMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetMe>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get total count of users
 */
export const userControllerGetUserCount = (
  params?: UserControllerGetUserCountParams,
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/users/count`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUserControllerGetUserCountQueryKey = (
  params?: UserControllerGetUserCountParams
) => {
  return [`/users/count`, ...(params ? [params] : [])] as const;
};

export const getUserControllerGetUserCountQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserCount>>,
  TError = unknown,
>(
  params?: UserControllerGetUserCountParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserCount>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetUserCountQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserCount>>
  > = ({ signal }) => userControllerGetUserCount(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserCount>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUserCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserCount>>
>;
export type UserControllerGetUserCountQueryError = unknown;

/**
 * @summary Get total count of users
 */

export function useUserControllerGetUserCount<
  TData = Awaited<ReturnType<typeof userControllerGetUserCount>>,
  TError = unknown,
>(
  params?: UserControllerGetUserCountParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserCount>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUserCountQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user by ID
 */
export const userControllerGetUserById = (id: string, signal?: AbortSignal) => {
  return customInstance<UserEntity>({
    url: `/users/${id}`,
    method: 'GET',
    signal,
  });
};

export const getUserControllerGetUserByIdQueryKey = (id?: string) => {
  return [`/users/${id}`] as const;
};

export const getUserControllerGetUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserById>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetUserByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserById>>
  > = ({ signal }) => userControllerGetUserById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserById>>
>;
export type UserControllerGetUserByIdQueryError = void;

/**
 * @summary Get user by ID
 */

export function useUserControllerGetUserById<
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserById>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUserByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update user by ID
 */
export const userControllerUpdateUser = (
  id: string,
  updateUserDto: UpdateUserDto
) => {
  return customInstance<UserEntity>({
    url: `/users/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateUserDto,
  });
};

export const getUserControllerUpdateUserMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateUser>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ['userControllerUpdateUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdateUser>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return userControllerUpdateUser(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateUser>>
>;
export type UserControllerUpdateUserMutationBody = UpdateUserDto;
export type UserControllerUpdateUserMutationError = void;

/**
 * @summary Update user by ID
 */
export const useUserControllerUpdateUser = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateUser>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationOptions = getUserControllerUpdateUserMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete user by ID
 */
export const userControllerDeleteUser = (id: string) => {
  return customInstance<UserEntity>({ url: `/users/${id}`, method: 'DELETE' });
};

export const getUserControllerDeleteUserMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerDeleteUser>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerDeleteUser>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['userControllerDeleteUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerDeleteUser>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userControllerDeleteUser(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerDeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDeleteUser>>
>;

export type UserControllerDeleteUserMutationError = void;

/**
 * @summary Delete user by ID
 */
export const useUserControllerDeleteUser = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerDeleteUser>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userControllerDeleteUser>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUserControllerDeleteUserMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get user with social accounts
 */
export const userControllerGetUserWithSocialAccounts = (
  id: string,
  signal?: AbortSignal
) => {
  return customInstance<UserEntity>({
    url: `/users/${id}/social-accounts`,
    method: 'GET',
    signal,
  });
};

export const getUserControllerGetUserWithSocialAccountsQueryKey = (
  id?: string
) => {
  return [`/users/${id}/social-accounts`] as const;
};

export const getUserControllerGetUserWithSocialAccountsQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUserControllerGetUserWithSocialAccountsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>
  > = ({ signal }) => userControllerGetUserWithSocialAccounts(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUserWithSocialAccountsQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>
>;
export type UserControllerGetUserWithSocialAccountsQueryError = void;

/**
 * @summary Get user with social accounts
 */

export function useUserControllerGetUserWithSocialAccounts<
  TData = Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserWithSocialAccounts>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUserWithSocialAccountsQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user with recent posts
 */
export const userControllerGetUserWithRecentPosts = (
  id: string,
  params?: UserControllerGetUserWithRecentPostsParams,
  signal?: AbortSignal
) => {
  return customInstance<UserEntity>({
    url: `/users/${id}/recent-posts`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUserControllerGetUserWithRecentPostsQueryKey = (
  id?: string,
  params?: UserControllerGetUserWithRecentPostsParams
) => {
  return [`/users/${id}/recent-posts`, ...(params ? [params] : [])] as const;
};

export const getUserControllerGetUserWithRecentPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>,
  TError = void,
>(
  id: string,
  params?: UserControllerGetUserWithRecentPostsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getUserControllerGetUserWithRecentPostsQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>
  > = ({ signal }) => userControllerGetUserWithRecentPosts(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUserWithRecentPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>
>;
export type UserControllerGetUserWithRecentPostsQueryError = void;

/**
 * @summary Get user with recent posts
 */

export function useUserControllerGetUserWithRecentPosts<
  TData = Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>,
  TError = void,
>(
  id: string,
  params?: UserControllerGetUserWithRecentPostsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserWithRecentPosts>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUserWithRecentPostsQueryOptions(
    id,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user by email
 */
export const userControllerGetUserByEmail = (
  email: string,
  signal?: AbortSignal
) => {
  return customInstance<UserEntity>({
    url: `/users/email/${email}`,
    method: 'GET',
    signal,
  });
};

export const getUserControllerGetUserByEmailQueryKey = (email?: string) => {
  return [`/users/email/${email}`] as const;
};

export const getUserControllerGetUserByEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserByEmail>>,
  TError = void,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserByEmail>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetUserByEmailQueryKey(email);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserByEmail>>
  > = ({ signal }) => userControllerGetUserByEmail(email, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!email,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserByEmail>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserControllerGetUserByEmailQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserByEmail>>
>;
export type UserControllerGetUserByEmailQueryError = void;

/**
 * @summary Get user by email
 */

export function useUserControllerGetUserByEmail<
  TData = Awaited<ReturnType<typeof userControllerGetUserByEmail>>,
  TError = void,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetUserByEmail>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserControllerGetUserByEmailQueryOptions(
    email,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
