/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateSocialAccountDto,
  LinkedInAccessTokenDto,
  SocialAccountControllerGetAccessToken201,
  SocialAccountControllerGetLinkedInAccessToken201,
  SocialAccountControllerUpsert201,
  SocialAccountEntity,
  TwitterAccessTokenDto,
  UpdateSocialAccountDto,
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

/**
 * @summary Create or update a social account
 */
export const socialAccountControllerUpsert = (
  createSocialAccountDto: CreateSocialAccountDto,
  signal?: AbortSignal
) => {
  return customInstance<SocialAccountEntity | SocialAccountControllerUpsert201>(
    {
      url: `/social-account/upsert`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSocialAccountDto,
      signal,
    }
  );
};

export const getSocialAccountControllerUpsertMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerUpsert>>,
    TError,
    { data: CreateSocialAccountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialAccountControllerUpsert>>,
  TError,
  { data: CreateSocialAccountDto },
  TContext
> => {
  const mutationKey = ['socialAccountControllerUpsert'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialAccountControllerUpsert>>,
    { data: CreateSocialAccountDto }
  > = (props) => {
    const { data } = props ?? {};

    return socialAccountControllerUpsert(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialAccountControllerUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerUpsert>>
>;
export type SocialAccountControllerUpsertMutationBody = CreateSocialAccountDto;
export type SocialAccountControllerUpsertMutationError = void;

/**
 * @summary Create or update a social account
 */
export const useSocialAccountControllerUpsert = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerUpsert>>,
    TError,
    { data: CreateSocialAccountDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof socialAccountControllerUpsert>>,
  TError,
  { data: CreateSocialAccountDto },
  TContext
> => {
  const mutationOptions =
    getSocialAccountControllerUpsertMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get all social accounts
 */
export const socialAccountControllerFindAll = (signal?: AbortSignal) => {
  return customInstance<SocialAccountEntity[]>({
    url: `/social-account`,
    method: 'GET',
    signal,
  });
};

export const getSocialAccountControllerFindAllQueryKey = () => {
  return [`/social-account`] as const;
};

export const getSocialAccountControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof socialAccountControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindAll>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSocialAccountControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialAccountControllerFindAll>>
  > = ({ signal }) => socialAccountControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SocialAccountControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerFindAll>>
>;
export type SocialAccountControllerFindAllQueryError = unknown;

/**
 * @summary Get all social accounts
 */

export function useSocialAccountControllerFindAll<
  TData = Awaited<ReturnType<typeof socialAccountControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindAll>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSocialAccountControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get all social accounts for the current user
 */
export const socialAccountControllerFindMine = (signal?: AbortSignal) => {
  return customInstance<SocialAccountEntity[]>({
    url: `/social-account/user/me`,
    method: 'GET',
    signal,
  });
};

export const getSocialAccountControllerFindMineQueryKey = () => {
  return [`/social-account/user/me`] as const;
};

export const getSocialAccountControllerFindMineQueryOptions = <
  TData = Awaited<ReturnType<typeof socialAccountControllerFindMine>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindMine>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSocialAccountControllerFindMineQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialAccountControllerFindMine>>
  > = ({ signal }) => socialAccountControllerFindMine(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindMine>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SocialAccountControllerFindMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerFindMine>>
>;
export type SocialAccountControllerFindMineQueryError = unknown;

/**
 * @summary Get all social accounts for the current user
 */

export function useSocialAccountControllerFindMine<
  TData = Awaited<ReturnType<typeof socialAccountControllerFindMine>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindMine>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSocialAccountControllerFindMineQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get social account by ID
 */
export const socialAccountControllerFindOne = (
  id: string,
  signal?: AbortSignal
) => {
  return customInstance<SocialAccountEntity>({
    url: `/social-account/${id}`,
    method: 'GET',
    signal,
  });
};

export const getSocialAccountControllerFindOneQueryKey = (id?: string) => {
  return [`/social-account/${id}`] as const;
};

export const getSocialAccountControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof socialAccountControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof socialAccountControllerFindOne>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSocialAccountControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialAccountControllerFindOne>>
  > = ({ signal }) => socialAccountControllerFindOne(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SocialAccountControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerFindOne>>
>;
export type SocialAccountControllerFindOneQueryError = void;

/**
 * @summary Get social account by ID
 */

export function useSocialAccountControllerFindOne<
  TData = Awaited<ReturnType<typeof socialAccountControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof socialAccountControllerFindOne>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSocialAccountControllerFindOneQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update social account by ID
 */
export const socialAccountControllerUpdate = (
  id: string,
  updateSocialAccountDto: UpdateSocialAccountDto
) => {
  return customInstance<SocialAccountEntity>({
    url: `/social-account/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateSocialAccountDto,
  });
};

export const getSocialAccountControllerUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerUpdate>>,
    TError,
    { id: string; data: UpdateSocialAccountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialAccountControllerUpdate>>,
  TError,
  { id: string; data: UpdateSocialAccountDto },
  TContext
> => {
  const mutationKey = ['socialAccountControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialAccountControllerUpdate>>,
    { id: string; data: UpdateSocialAccountDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return socialAccountControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialAccountControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerUpdate>>
>;
export type SocialAccountControllerUpdateMutationBody = UpdateSocialAccountDto;
export type SocialAccountControllerUpdateMutationError = void;

/**
 * @summary Update social account by ID
 */
export const useSocialAccountControllerUpdate = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerUpdate>>,
    TError,
    { id: string; data: UpdateSocialAccountDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof socialAccountControllerUpdate>>,
  TError,
  { id: string; data: UpdateSocialAccountDto },
  TContext
> => {
  const mutationOptions =
    getSocialAccountControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete social account by ID
 */
export const socialAccountControllerRemove = (id: string) => {
  return customInstance<SocialAccountEntity>({
    url: `/social-account/${id}`,
    method: 'DELETE',
  });
};

export const getSocialAccountControllerRemoveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialAccountControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['socialAccountControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialAccountControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return socialAccountControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialAccountControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerRemove>>
>;

export type SocialAccountControllerRemoveMutationError = void;

/**
 * @summary Delete social account by ID
 */
export const useSocialAccountControllerRemove = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof socialAccountControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getSocialAccountControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get Twitter OAuth 2.0 authorization URL
 */
export const socialAccountControllerGetRequestToken = (
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/social-account/twitter/request-token`,
    method: 'GET',
    signal,
  });
};

export const getSocialAccountControllerGetRequestTokenQueryKey = () => {
  return [`/social-account/twitter/request-token`] as const;
};

export const getSocialAccountControllerGetRequestTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSocialAccountControllerGetRequestTokenQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>
  > = ({ signal }) => socialAccountControllerGetRequestToken(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SocialAccountControllerGetRequestTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>
>;
export type SocialAccountControllerGetRequestTokenQueryError = unknown;

/**
 * @summary Get Twitter OAuth 2.0 authorization URL
 */

export function useSocialAccountControllerGetRequestToken<
  TData = Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetRequestToken>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getSocialAccountControllerGetRequestTokenQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Twitter access token and create social account
 */
export const socialAccountControllerGetAccessToken = (
  twitterAccessTokenDto: TwitterAccessTokenDto,
  signal?: AbortSignal
) => {
  return customInstance<void | SocialAccountControllerGetAccessToken201>({
    url: `/social-account/twitter/access-token`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: twitterAccessTokenDto,
    signal,
  });
};

export const getSocialAccountControllerGetAccessTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>,
    TError,
    { data: TwitterAccessTokenDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>,
  TError,
  { data: TwitterAccessTokenDto },
  TContext
> => {
  const mutationKey = ['socialAccountControllerGetAccessToken'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>,
    { data: TwitterAccessTokenDto }
  > = (props) => {
    const { data } = props ?? {};

    return socialAccountControllerGetAccessToken(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialAccountControllerGetAccessTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>
>;
export type SocialAccountControllerGetAccessTokenMutationBody =
  TwitterAccessTokenDto;
export type SocialAccountControllerGetAccessTokenMutationError = unknown;

/**
 * @summary Get Twitter access token and create social account
 */
export const useSocialAccountControllerGetAccessToken = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>,
    TError,
    { data: TwitterAccessTokenDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof socialAccountControllerGetAccessToken>>,
  TError,
  { data: TwitterAccessTokenDto },
  TContext
> => {
  const mutationOptions =
    getSocialAccountControllerGetAccessTokenMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get LinkedIn OAuth 2.0 authorization URL
 */
export const socialAccountControllerGetLinkedInAuthUrl = (
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/social-account/linkedin/auth-url`,
    method: 'GET',
    signal,
  });
};

export const getSocialAccountControllerGetLinkedInAuthUrlQueryKey = () => {
  return [`/social-account/linkedin/auth-url`] as const;
};

export const getSocialAccountControllerGetLinkedInAuthUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getSocialAccountControllerGetLinkedInAuthUrlQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>
  > = ({ signal }) => socialAccountControllerGetLinkedInAuthUrl(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SocialAccountControllerGetLinkedInAuthUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>
>;
export type SocialAccountControllerGetLinkedInAuthUrlQueryError = unknown;

/**
 * @summary Get LinkedIn OAuth 2.0 authorization URL
 */

export function useSocialAccountControllerGetLinkedInAuthUrl<
  TData = Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAuthUrl>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getSocialAccountControllerGetLinkedInAuthUrlQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get LinkedIn access token and create social account
 */
export const socialAccountControllerGetLinkedInAccessToken = (
  linkedInAccessTokenDto: LinkedInAccessTokenDto,
  signal?: AbortSignal
) => {
  return customInstance<void | SocialAccountControllerGetLinkedInAccessToken201>(
    {
      url: `/social-account/linkedin/access-token`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: linkedInAccessTokenDto,
      signal,
    }
  );
};

export const getSocialAccountControllerGetLinkedInAccessTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>,
    TError,
    { data: LinkedInAccessTokenDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>,
  TError,
  { data: LinkedInAccessTokenDto },
  TContext
> => {
  const mutationKey = ['socialAccountControllerGetLinkedInAccessToken'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>,
    { data: LinkedInAccessTokenDto }
  > = (props) => {
    const { data } = props ?? {};

    return socialAccountControllerGetLinkedInAccessToken(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SocialAccountControllerGetLinkedInAccessTokenMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>
  >;
export type SocialAccountControllerGetLinkedInAccessTokenMutationBody =
  LinkedInAccessTokenDto;
export type SocialAccountControllerGetLinkedInAccessTokenMutationError =
  unknown;

/**
 * @summary Get LinkedIn access token and create social account
 */
export const useSocialAccountControllerGetLinkedInAccessToken = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>,
    TError,
    { data: LinkedInAccessTokenDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof socialAccountControllerGetLinkedInAccessToken>>,
  TError,
  { data: LinkedInAccessTokenDto },
  TContext
> => {
  const mutationOptions =
    getSocialAccountControllerGetLinkedInAccessTokenMutationOptions(options);

  return useMutation(mutationOptions);
};
