/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Uploader Docs
 * documentation for api enpoints of the Uploader.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CreateOrderResponseDto,
  VerifyPaymentDto,
  VerifyPaymentResponseDto,
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';

export const paymentControllerCreateOrder = (signal?: AbortSignal) => {
  return customInstance<CreateOrderResponseDto>({
    url: `/payment/create-order`,
    method: 'POST',
    signal,
  });
};

export const getPaymentControllerCreateOrderMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCreateOrder>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerCreateOrder>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['paymentControllerCreateOrder'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerCreateOrder>>,
    void
  > = () => {
    return paymentControllerCreateOrder();
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerCreateOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerCreateOrder>>
>;

export type PaymentControllerCreateOrderMutationError = unknown;

export const usePaymentControllerCreateOrder = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCreateOrder>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerCreateOrder>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getPaymentControllerCreateOrderMutationOptions(options);

  return useMutation(mutationOptions);
};
export const paymentControllerVerifyPayment = (
  verifyPaymentDto: VerifyPaymentDto,
  signal?: AbortSignal
) => {
  return customInstance<VerifyPaymentResponseDto>({
    url: `/payment/verify`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verifyPaymentDto,
    signal,
  });
};

export const getPaymentControllerVerifyPaymentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerVerifyPayment>>,
    TError,
    { data: VerifyPaymentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerVerifyPayment>>,
  TError,
  { data: VerifyPaymentDto },
  TContext
> => {
  const mutationKey = ['paymentControllerVerifyPayment'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerVerifyPayment>>,
    { data: VerifyPaymentDto }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerVerifyPayment(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerVerifyPaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerVerifyPayment>>
>;
export type PaymentControllerVerifyPaymentMutationBody = VerifyPaymentDto;
export type PaymentControllerVerifyPaymentMutationError = unknown;

export const usePaymentControllerVerifyPayment = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerVerifyPayment>>,
    TError,
    { data: VerifyPaymentDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerVerifyPayment>>,
  TError,
  { data: VerifyPaymentDto },
  TContext
> => {
  const mutationOptions =
    getPaymentControllerVerifyPaymentMutationOptions(options);

  return useMutation(mutationOptions);
};
