# Dockerfile.api (for NestJS app)
FROM node:20-slim

RUN echo "--- RUNNING MODIFIED DOCKERFILE ---"

WORKDIR /app

RUN node -e "require('dns').lookup('prisma.io', (err) => { if (err) throw err; console.log('Network is OK'); })"

# Install pnpm
RUN npm install -g pnpm

# Install build tools for native addons and curl for health checks
RUN apt-get update && apt-get install -y python3 make g++ curl openssl procps iputils-ping && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Test network connectivity
RUN ping -c 4 prisma.io

# Copy the full monorepo context
COPY . .

RUN cat ./apps/api/src/social-account/social-account.service.ts

# Install all dependencies
RUN pnpm install --frozen-lockfile

# Generate Prisma client - IMPORTANT!
RUN pnpm --filter db run prisma:generate

# Build the api and its dependencies
RUN pnpm --filter api... build

# Expose port
EXPOSE 3001 9229

# Start the api
CMD ["pnpm", "--filter=api", "run", "dev"]